service: wvtest-puppeteer

provider:
  name: aws
  region: us-east-1
  environment:
      STAGE: production
      BUCKET_NAME: wvtest-prod
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
          - s3:DeleteObject
          - s3:PutObjectAcl
        Resource:
          - '*'

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  app:
    runtime: nodejs12.x
    handler: index.handler
    events:
      - http:
        path: /generate-pdf
        method: post

plugins:
  - serverless-python-requirements
  - serverless-plugin-include-dependencies
  - serverless-apigw-binary

package:
  excludeDevDependencies: false
  exclude:
    - node_modules/**
