# Mostly copied from https://medium.com/swlh/how-to-create-pdf-in-lambda-using-puppeteer-6355348b8a82
# Modifications:
# - NodeJS 12?
# - No need for ServerlessDomainManager & customDomain.
# - No need for Webpack.
# - Maybe don't need serverless-offline?

org: topherhunt
app: wvtest-puppeteer
service: wvtest-puppeteer-generate-pdf

provider:
  name: aws
  region: us-east-1
  versionFunctions: false
  runtime: nodejs12.x
  stage: production
  apiGateway:
    binaryMediaTypes:
      - "application/pdf"

functions:
  generate-pdf:
    handler: index.handler
    events:
      - http:
          path: /generate-pdf
          method: post
